server:
  port: 8981
#  servlet:
#    context-path: /consumer

spring:
  # 配置 rabbitMQ 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    virtual-host: "/"
#    connection-timeout: 5000
    listener:
      simple:
        concurrency: 5              # 并发数量
        max-concurrency: 10         # 最大并发数量
        acknowledge-mode: manual    # 开启手动签收
#        acknowledge-mode: auto
        prefetch: 1                 # 限制一个线程每次只消费一个，并发数为5，则能一次接收5个
      direct:
        retry:                      # Spring消费者失败重试
          enabled: true             # 【开关】开启消费者失败重试
          initial-interval: 1000    # 初识的失败等待时长为1秒（第一次失败后1s重试）
          multiplier: 1             # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval（举例：倍数*第一次等待时长1s，这样子永远都是1s）
          max-attempts: 3           # 最大重试次数
          stateless: true           # （默认为true）true无状态；false有状态【如果业务中包含事务，这里改为false】
          #（备注：如果设置为false，那么Spring在重试的时候保留事务——消耗性能，所以没有事务时设置为true提升性能）
          max-interval: 10000       # 最大等待时长，大于此时长的一律按最大时长来计算