server:
  port: 8980
#  servlet:
#    context-path: /provider

spring:
  # 配置 rabbitMQ 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    virtual-host: "/"