server:
  port: 8980
#  servlet:
#    context-path: /provider

spring:
  # 配置 rabbitMQ 服务器
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#    virtual-host: "/"
#    connection-timeout: 5000
#    publisher-confirm-type: correlated  # 消息成功确认 - 三种确认模式：correlated、none、simple
#      #    publisher-confirms: true            # 弃用
#    publisher-returns: true             # 消息失败确认：
#    template:
#      mandatory: true                   # 手动签收机制